name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🪲 Fixes"
    labels:
      - "bug"
  - title: "🛠️ Maintenance"
    labels:
      - "maintenance"
  - title: "📦 Dependency Updates"
    labels:
      - "dependencies"
  - title: "📖 Documentation Updates"
    labels:
      - "documentation"

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

template: |
  ## What's Changed
  $CHANGES