name: Check and Apply PR Labels

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug - Print environment variables
        run: env

      - name: Set up GitHub Script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            const prefix = branch.split('/')[0];
            const label = prefix.toLowerCase();

            const labels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const labelNames = labels.data.map(l => l.name.toLowerCase());

            if (labelNames.includes(label)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [label]
              });
              console.log(`Applied label: ${label}`);
            } else {
              console.log(`Label "${label}" not found in repo; skipping.`);
            }

      - name: Required Labels - Minimum
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: |
            maintenance
            bug
            feature
            enhancement
            documentation
          add_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Required Labels - Do Not Merge
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: "do not merge"
          add_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}