name: Create Release on Tag

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string
        description : "- 'v*.*.*'"
  pull_request:
    branches:
      - master
  tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Generate Changelog with Release Drafter
        uses: release-drafter/release-drafter@v6.1.0
        id: generate_changelog
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: 'go.mod'

      - name: Go Version
        run: go version
        continue-on-error: true

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            ${{ steps.generate_changelog.outputs.body }}
          draft: false
          prerelease: false
