name: Create Release on Tag

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string
        description : "- 'v*.*.*'"
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Generate Changelog with Release Drafter
        uses: release-drafter/release-drafter@v6.1.0
        id: generate_changelog
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: 'go.mod'

      - name: Go Version
        run: go version
        continue-on-error: true

      - name: Upload AndroidLibSocksLite to release
        if: github.event.inputs.release_tag != ''
        uses: svenstaro/upload-release-action@v2
        with:
          file: netcheck.go
          tag: ${{ github.event.inputs.release_tag }}
          file_glob: true
