name: Update Latest Tag

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          description: 'latest'