name: Update Latest Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Ensure full history to update tags

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Create or update 'latest' tag
        run: |
          echo "Setting the latest commit to point to tag 'latest'"
          # Force-update the 'latest' tag to point to this commit
          git tag -f latest "${{ github.sha }}"
          git push origin -f latest