name: Update Latest Tag

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest